export const privacyPolicyData = [
  {
    id: 1,
    title: "1. GENERAL",
    desc: `This Privacy Policy (“Policy”) describes the policies and procedures on the collection, use, disclosure and protection of Your information by Bigsurmoon private limited (“we”, “us” and “our”), a private limited company having its registered office at Bethlehem, Kilivayal, 691551, Adoor, India.
 
        This document is an electronic record and is governed by the provisions under the Information Technology Act, 2000 and rules made there under as may be applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
         
        We offer different services to different clients or users (“User”, “your” or “you”) and the kind of information we collect is based on the type of Services (as set out below) you are taking from us. By receiving, using, accessing, or subscribing to our services, you agree to be bound by the terms of this Privacy Policy and consent to the collection, storage, possession, dealing, handling, sharing, disclosure or transfer of your information in accordance with the terms of this Privacy Policy. We shall not use the User’s information in any manner except as provided under this Privacy Policy.
         
        We reserve the right to make changes to this Privacy Policy at any time and for any reason and shall update the “Last Updated” date of this Privacy Policy whenever we do so. Any changes or modifications will be effective immediately upon posting the updated Privacy Policy on the website, and you waive the right to receive specific notice of each such change or modification.
        `,
  },
  {
    id: 2,
    title: "2. OUR SERVICES AND TYPE OF INFORMATION COLLECTED",
    desc: `Our Services include creating and enabling 3D models (“3D”), augmented reality (“AR”) based product discovery experiences individually or through Bigsurmoon’s proprietary platform (collectively or individually referred to as “Services”).
 
    You are under no obligation to provide us with information of any kind, however your refusal to do so may prevent you from using some of our Services. We may also use information we collect for internal purposes such as auditing, data analysis and research to improve our products, services and customer communications.
     
    Without limitation, following is the information we collect if you avail our Services from the below options:
     
    2.1 Option 1: Services without using our proprietary Mobile/Web App:
     
    We may collect the following information in this case:
     
    Catalog Information: features, images or videos of your products or services, specifications, URLs and lists of SKUs, catalog name and details.
     
    Technical Information: Internet Protocol (“IP”) address, your browser type, type of your operating system, your access/engagement times, events such as impressions, interaction and engagement with our experiential Services, the time and date of your use of the Services, and other statistics with the use of an analytical tool.
     
    Other Information: Any kind of communications with you, your feedback and opinions on our Services, your survey responses, program-specific information when you participate in any marketing programs.
     
    2.2 Option 2: Services via our proprietary Mobile/Web App:
     
    In addition to the information captured in Option 1, we may collect the following information in this case:
     
    Personal Information: Name, e-mail address, or any other personal information provided in responses to surveys or questionnaires or at the time of sign in/ sign up.
     
    Financial Information: A third party payment gateway provider may be required to collect certain financial information from you including, but not restricted to, your credit/debit card number or your bank account details. All Financial Information collected from you by such third party payment gateway providers will be used only for billing and payment processes. The Financial Information collected from you is transacted through secure digital platforms of approved payment gateways which are under encryption, thereby complying with reasonably expected technology standards. The verification of the Financial Information shall be accomplished only by you through a process of authentication in which we shall have no role to play and hence, we shall bear no liability in relation to the same. We shall neither be liable nor responsible for any actions or inactions of third-party payment gateway providers or any breach of conditions, representations and warranties given by them. We shall also not be obligated to mediate or resolve any dispute or disagreement between you and such third-party payment service providers.
     
     
    2.3 Option 3: Services via our Web App built on headless commerce platforms
       
    In case you avail our Services through our WebApp built on headless commerce platforms (namely including but not limited to Shopify, Big Commerce etc.), we additionally to the above may also get information shared by such platforms in accordance with their own terms and conditions of use.
    `,
  },
  {
    id: 3,
    title: "3. COOKIES",
    desc: `Our Services do not use these “cookies” explicitly. Our web servers or affiliates who provide analytics and performance enhancement services collect IP addresses, operating system details, browsing details, device details and language settings.`
  },
  {
    id: 4,
    title: "4. USE OF YOUR INFORMATION",
    desc: `We may collect, use or process your information for the following purposes:
 
    4.1 For creating, managing and giving you access to your registered account for Bigsurmoon Services.
    4.2 To develop, deliver, process and improve our products, services, content in order to personalize and improve your experience.
    4.3 For internal analytical and research purposes such as auditing, data analysis and research to improve our products, services and customer communications.
    4.4 To meet any legal or regulatory requirement or comply with a request from any governmental or judicial authority.
    4.5 To resolve any request, dispute, grievance or complaint raised by you in relation to your use of the Bigsurmoon Services.
    4.6 To detect or monitor any fraudulent or illegal activity on the Bigsurmoon platform.
    4.7 To develop, deliver, process and improve our products, services, content in order to personalize and improve your experience.
    4.8 For marketing and promoting our Services to you.
    4.9 To carry out our obligations arising from any contract entered into between you and us.
    4.10 For protection against and prevent fraud, illegal activity, harm, financial loss and other legal or information security risks.
     
    Where required under applicable law, we will only use your Personal Information with your consent; as necessary to provide you with products and/or services; to comply with a legal obligation; or when there is a legitimate interest that necessitates the use.
     
    You shall have the opportunity to stop receiving to opt out and stop receiving marketing communications from us. In order to do the same, you shall be required to send an email to getsupport@Bigsurmoon.ai.
    `
  },
  {
    id: 5,
    title: "5. DISCLOSURE OF INFORMATION COLLECTED",
    desc: `We may share information we have collected about you in certain situations such as follows:
 
    We may disclose your information when such disclosure is requisitioned under any law or judicial decree or when we, in our sole discretion, deem it necessary in order to protect our rights or the rights of other Users, to prevent harm to persons or property, to fight fraud and credit risk.
     
    We may from time to time be required to disclose the information collected from you to our trusted third-party service providers who assist may assist us in processes including but not limited to payment processing, customer service, advertising and marketing, security, and performance monitoring, maintaining or servicing account, hosting, processing and fulfilment of demo requests, research, auditing, data analysis etc.
    `
  },
  {
    id: 6,
    title: "6. STORAGE AND RETENTION OF INFORMATION",
    desc: `We store your data on online servers ensuring best possible protection from our end. We intend to protect it in encrypted format and also take back-up at defined intervals to ensure there is minimum data loss in case of any unfortunate circumstances.
 
    We retain or store your Information after we cease providing Services to you, to the extent necessary to comply with our legal and regulatory obligations, and for the purpose of fraud monitoring, detection, and prevention or for internal purposes such as auditing, data analysis and research to improve our products, services and customer communications.
     
    We also retain your Information to comply with our tax, accounting, and financial reporting obligations, where we are required to retain the data by our contractual commitments to our financial partners, and where data retention is mandated by the payment methods that we support. Where we retain data, we do so in accordance with any limitation periods and records retention obligations that are imposed by applicable law.
    `
  },
  {
    id: 7,
    title: "7. SECURITY OF DATA",
    desc: `The security of your personal information is important to us. We take precautions, including administrative, technical, procedural, organizational and physical measures, to safeguard your personal information against loss, theft and misuse, as well as against unauthorized access, disclosure, alteration and destruction. If you suspect any misuse or loss or unauthorised access to your Data, please let us know immediately by contacting us by e-mail on getsupport@Bigsurmoon.ai.
 
    We have a standard SSL certification which basically helps us create a secure connection between our server and the user to render any information or action. Some of the safeguards we use are firewalls and data encryption, physical access controls to our data centers and information access authorization controls. Only user passwords are encrypted in standard encryption and stored because generally users use the same password on multiple sites, to prevent any kind of theft, piracy, or unauthorized access. If you believe your account has been abused or hacked, please contact us by sending us an email at info@bigsurmoon.com
     
    We do not sell, transfer, or rent your Personal Information to third parties for their marketing purposes without your explicit consent and we only use your information as described in the Privacy Policy. We view protection of your privacy as a very important community principle. We understand that you and your Personal Information is one of our most important assets.
    `
  },
  {
    id: 8,
    title: "8. INFORMATION FROM MINORS",
    desc: `We do not knowingly solicit data from or market to children under 18 years of age. By using the Website, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the Services. If we learn that personal information from users less than 18 years of age has been collected, we will take reasonable measures to promptly delete such data from our records. If you become aware of any data we may have collected from children under age 18, please contact us at info@bigsurmoon.com.`
  },
  {
    id: 9,
    title: "9. OWNERSHIP OF RIGHTS ",
    desc: `All rights, including copyright, in this ‘Services’ are owned by or are licensed to us. Any use of these Services or its contents, including copying or storing it, in whole or in part, other than for your own, personal or non-commercial use is prohibited without our permission. You are prohibited from modifying, copying, distributing, transmitting, displaying, printing, publishing, selling, licensing, creating derivative works, reverse-engineering or mirroring or using any content available on or through our Services for commercial or public purposes. You may not modify, distribute or re-post something on these Services for any purpose. We will retain your information and any data for the period necessary to fulfil the purposes outlined in this Privacy Policy unless a longer retention period is required or permitted under the applicable law.`
  },
  {
    id: 10,
    title: "10. MODIFICATION",
    desc: `We reserve the right to amend this Privacy Policy at any time. The policies, as and how modified, shall be updated on our Website. You are encouraged to periodically review this Privacy Policy to stay informed of updates. You will be deemed to have been made aware of, will be subject to, and will be deemed to have accepted the changes in any revised Privacy Policy by your continued use of the Services after the date such revised Privacy Policy is posted.`
  },{
    id: 11,
    title: "11. JURISDICTION",
    desc: `If you choose to visit our website and use our Services, your visit and any dispute over privacy is subject to this Policy. In addition to the foregoing, any disputes arising under this policy shall be governed by the laws of India and exclusive jurisdiction of the courts located at Bengaluru, Karnataka.`
  },
  {
    id: 12,
    title: "12. CONTACT",
    desc: `In case you have any questions, grievances or complaints about this Privacy Policy, or the Bigsurmoon platform or Services you may contact us at info@bigsurmoon.com`
  }
];
